umd:
  name: 'University of Maryland Special Collections and University Archives'
  description: 'Special Collections and University Archives collect and provide access to material related to the history of the University of Maryland, the state of Maryland, literature and rare books, and American history, especially as it relates to labor, mass media, and the performing arts. Use our books, manuscripts, photographs and audio/visual materials to enhance your research.'
  building: 'Hornbake Library'
  address1: '4130 Campus Drive'
  address2: ''
  city: 'College Park'
  state: 'MD'
  zip: '20742'
  country: 'USA'
  phone: '301-405-9212'
  contact_info: 'askhornbake@umd.edu'
  thumbnail_url: "https://www.lib.umd.edu/binaries/content/gallery/public/special/mbook_tall.jpg"
scpa:
  name: 'Michelle Smith Performing Arts Library'
  description: 'The Michelle Smith Performing Arts Library (MSPAL) is the central location on the College Park campus for music, theatre, and dance materials. The circulating, reference, serial, and special collections include 56,000 books, 156,000 musical scores, 130,000 audio and video recordings, 4500 microform titles, and 281 active journal subscriptions.'
  building: 'Michelle Smith Performing Arts Library'
  address1: '8270 Alumni Drive'
  address2: ''
  city: 'College Park'
  state: 'MD'
  zip: '20742'
  country: 'USA'
  phone: ''
  contact_info: 'scpa@umd.edu'
  thumbnail_url: "https://www.lib.umd.edu/binaries/content/gallery/public/ipam/home/rachhandstint.gif"
